### ISSUE TITLE
no reaction in wake-word - only status "listen"

### ISSUE THREAD

**Issue by reschresch** [johanneskropf/node-red-contrib-personal-wake-word#1]
Hello,
I try to implement a wake-word (on my RPi 4 with Raspbian) in Node-Red. 
It looks good, I follow your instructions and the button "wakeword" is in the status "listen" - and thats all.
My sox-record give a "stream of raw buffers". How I can see if there is something to do for the "wakeword"? The status "Listen" noch changed.
I test the "sox-record" and change the output to a wav. That's OK, I got a correct wav-file. 
In the sox-record-configuration there is a "processing buffer" where I don't find any info whats the correct value. I try 4096.
With best regards,
René

**Comment by johanneskropf** [comment]
Hello, sorry for the slow answer.
Lets clear up a few questions about your set up first:
+ are both the sox record node that is streaming and the one you recorded your samples with set correctly to output 16000 hz 16 bit mono audio?
+ how many samples are you using and are you sure the path you have given to them is correct?
+ you can leave the processing buffer as is

**Comment by johanneskropf** [comment]
Ok i just saw that the author of the wake word module itself changed something and this might habe broken my node. Let me check this when im home and if this is the case i will fix it tonight and publish an update…

**Comment by johanneskropf** [comment]
Ok can you please try now? Sorry I was very busy but finally got some downtime to hopefully fix this.
Should be working now in 0.2.6 which I just pushed to npm/github/node-red
